version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - dispatcher-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dispatcher-network

networks:
  dispatcher-network:
    driver: bridge
